[book]
authors = ["sys-ta"]
language = "zh"
multilingual = false
src = "src"
title = "Introduction to NSCSCC"

[build]
create-missing = false

[output.html]
default-theme = "light"
additional-css = ["custom.css"]
curly-quotes = true
no-section-label = true

[output.html.fold]
enable = true
level = 1

[preprocessor.katex]
